# Generated by Django 3.2 on 2023-07-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230729_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
